### ISSUE TITLE
Kibana instances increasing on Docker

### ISSUE THREAD

**Issue by mathewvino** [elastic/kibana-docker#12]
I am trying to run kibana5.1 and elasticsearch5.1 on docker using docker-compose.

1)	Using volumes for elastic search data
2)	Using volume for kibana config file

The challenge I am facing is when I use monitoring on kibana dashboard the no.of instances is increasing each time when I bounce docker-compose

•	When I clear the elastic volumes for data indices first time the no.of instances show up 1
•	Second time its increases to 2 …. So on
•	If we clear the elastic volume data and bounce again the instance will be 1 and again each time we bounce the no.of instances increase for kibana

Any help is really appreciated.

Thanks

docker-compose:

``` yaml
version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /c/Users/dockeroffice/elknode1/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk_docker
  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.1
    ports:
      - 5601:5601
    networks:
      - elk_docker
    volumes:
      - /c/Users/dockeroffice/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch1
  
 
networks:
  elk_docker:
    driver: bridge
```

![image](https://cloud.githubusercontent.com/assets/11719809/21737112/d6a0fb1e-d42a-11e6-8c41-2fc6ca44a12c.png)
