### ISSUE TITLE
no x-pack?

### ISSUE THREAD

**Issue by robellison** [elastic/kibana-docker#14]
is this available without x-pack integration or are there options to not expect it?
the docs suggest it is x-pack only.

**Comment by jarpy** [comment]
Hi @robellison,

We ship the images with X-Pack installed, but we tried to make it easy to disable the features if you don't want them. Here's an example `docker-compose.yml` that shows one way to turn off X-Pack Monitoring and Security.

``` yaml
---
version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
    networks:
      - elastic-stack
    ports:
      - '5601:5601'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    networks:
      - elastic-stack

networks:
  elastic-stack:
```

That uses the environment-to-CLI mapping system that we have in the images. Sorry about the inconsistency with the formatting of variable names. We plan to fix that in the next major version.

You can also [achieve the same thing in `elasticsearch.yml` and `kibana.yml`](https://www.elastic.co/guide/en/x-pack/index.html) if you prefer.
