### ISSUE TITLE
elasticsearch.hosts or elasticsearch.url are not picked up at all in version 6.7.0

### ISSUE THREAD

**Issue by liyimeng** [elastic/kibana-docker#140]
no matter how I configure these two variable, kibana always try to connect to http://elasticsearch:9200

Downgrade to 6.6.0, the problem seems to gone.

**Comment by liyimeng** [comment]
neither 6.7.1
but works for 6.6.2 and 6.6.0

**Comment by xeraa** [comment]
Can you be a bit more specific in how you are running the stack?

I've just tested the following Docker Compose setup with 6.7.0 and it works fine:

```yml
---
version: '2'
services:

  elasticsearch-foo:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-foo:9200
    links:
      - elasticsearch-foo
    ports:
      - 5601:5601

volumes:
  esdata1:
    driver: local
```

When I remove the `- ELASTICSEARCH_HOSTS=http://elasticsearch-foo:9200` it breaks with a lot of `Unable to revive connection: http://elasticsearch:9200/` messages.
