### ISSUE TITLE
Unable to start Kibana 5.3.0 without X-Pack

### ISSUE THREAD

**Issue by kylegordon** [elastic/kibana-docker#27]
Our ElasticSearch 5.3.0 cluster does not have X-Pack installed, and I have no plans to install it.

However, when running Kibana 5.3.0 Docker image, it consistently switches to Red status due to the cluster not supporting X-Pack. How do you disable it completely?

I am running Kibana locally as below...

docker run  -e ELASTICSEARCH_URL=http://10.2.8.243:9200 -e KIBANA_INDEX=.kibana -e XPACK_SECURITY_ENABLED=false -e XPACK_MONITORING_ENABLED=false -e SERVER_NAME:localhost -p 5601:5601 docker.elastic.co/kibana/kibana:5.3.0

**Comment by jarpy** [comment]
Indeed. That's ugly, sorry.

Even with all X-Pack components disabled:
``` yaml
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - XPACK_GRAPH_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
```

...the exeception is still thrown:

```
Unhandled rejection [illegal_argument_exception] No endpoint or operation is available at [_xpack]
```

For now, I would create a custom image with:
```dockerfile
FROM docker.elastic.co/kibana/kibana:5.3.1
RUN bin/kibana-plugin remove x-pack && \
    kibana 2>&1 | grep -m 1 "Optimization of .* complete" # [1]
```

Would it be worth have a single flag to truly disable all X-Pack functionality? @ycombinator?

<sub>[1] _See https://github.com/elastic/kibana/issues/6057 for the optimization trick._<sub>

**Comment by ycombinator** [comment]
> Unhandled rejection [illegal_argument_exception] No endpoint or operation is available at [_xpack]

That particular exception is being thrown because there is apparently no x-pack installed on the Elasticsearch side. 

I can see the value in having a single flag to disable all of X-Pack but it seems to me the issue here might be that the kibana docker image is doing too much? Maybe there should be a base kibana docker image that is only OSS kibana, and another one that layers on the x-pack plugin via `RUN bin/kibana-plugin install x-pack`?

**Comment by sebamontini** [comment]
@ycombinator @jarpy any update on this? we try to build our own custom images which does the `kibana-plugin remove x-pack` but doesn't seems to be working as expected.

**Comment by jarpy** [comment]
We will likely release an OSS-only image soon.

What's going wrong with your custom image?

**Comment by akailash** [comment]
- xpack.ml.enabled=false
Have you used this setting as well?

**Comment by sebamontini** [comment]
@akailash no need for that since we're using kibana and ES 5.1.2

@jarpy don't really now, I did exactly what you said in your previous comment (except for the version)
and when the image starts, i get that xpack is still installed

**Comment by sebamontini** [comment]
the workaround we found was to still use the image form docker hub which doesn't have xpack installed and works great (unless the 5.1.2 does)

**Comment by pavlod** [comment]
I am just start kibana-docker like this:

docker run docker.elastic.co/kibana/kibana:5.5.1 /bin/bash -c 'bin/kibana-plugin remove x-pack ; /usr/local/bin/kibana-docker'

**Comment by xbulat** [comment]
`/bin/bash -c '/usr/share/kibana/bin/kibana-plugin remove x-pack;/usr/local/bin/kibana-docker'`

**Comment by sebamontini** [comment]
you could just use the old docker hub image: https://hub.docker.com/_/kibana/ which doesn't have xpack at all

it supports up to 5.6.0...hopefully they will have this fixed before that version

**Comment by Russell-IO** [comment]
This seems to do the trick for me (n.b. am using ansbile ... so adjust how you pass in environment vars accordingly)
```
       env:
         ELASTICSEARCH_URL: "http://{{ ansible_default_ipv4.address }}:9200"
         XPACK_GRAPH_ENABLED: false
         XPACK_MONITORING_ENABLED: false
         XPACK_REPORTING_ENABLED: false
         XPACK_SECURITY_ENABLED: false
         XPACK_ML_ENABLED: false
```
