### ISSUE TITLE
Reporting not working, missing fontconfig and freetype

### ISSUE THREAD

**Issue by WaaZaa666** [elastic/kibana-docker#31]
After running a fresh kibana:5.4.0, reporting is complaining about missing fontconfig  and freetype. 

![1](https://cloud.githubusercontent.com/assets/28536686/25809099/5a3350e4-340c-11e7-8db2-93bbb374ddcb.PNG)
![2](https://cloud.githubusercontent.com/assets/28536686/25809106/5c8a3fd8-340c-11e7-8506-16cca027ff8a.PNG)

Running it from docker-compose as such, together with elasticsearch-docker:

```
 kibana:
    depends_on:
      - elasticsearch1
    image: docker.elastic.co/kibana/kibana:5.4.0
     environment:
       ELASTICSEARCH_URL: http://elasticsearch1:9200
    ports:
       - 5601:5601
     networks:
       - esnet
```
