### ISSUE TITLE
Troubles using the docker image > SERVER_HOST environment var

### ISSUE THREAD

**Issue by florianbepunkt** [elastic/kibana-docker#33]
I had a lot of troubles using the official docker image. There seems something off with the SERVER_HOST env config. Using localhost or not setting it at all prevents me from accessing the kibana server (it either not reachable or crashes on running the container). I'm using Docker 17.03.1-ce-mac12 (17661)

Here's my working Dockerfile in case anyone else has troubles getting this to work:

```
# this should match your ES version, in my case 5.1.1
FROM docker.elastic.co/kibana/kibana:5.1.1

# since I don't have X-Pack on my cluster, we remove X-pack from the image
RUN bin/kibana-plugin remove x-pack && \
    kibana 2>&1 | grep -m 1 "Optimization of .* complete" # [1]

# url to the cluster, I specified protocol and port here as well (using bonsai)
ENV ELASTICSEARCH_URL=https://yoururltoescluster:443

# don't know why but this was the only value that worked, server is accessible under http://0.0.0.0:5601/
ENV SERVER_HOST=0.0.0.0

# only set these if you need basic auth
ENV ELASTICSEARCH_USERNAME=YOURUSERNAME
ENV ELASTICSEARCH_PASSWORD=YOURPASS

EXPOSE 5601
```

**Comment by jarpy** [comment]
The answer here is to think about what `localhost` means in a container context. Within the Kibana container, `localhost` _is_ the Kibana container. So if you set `SERVER_HOST` to `localhost`, you can only access Kibana over the (virtual) loopback interface from inside the container itself (probably not what anybody wants).

That's why [we default `SERVER_HOST` to `"0"`](https://github.com/elastic/kibana-docker/blob/5.1/build/kibana/config/kibana.yml) so you don't need to set it at all. Because of this, very little configuration is needed, and this `docker-compose.yml`, for example, works as expected:

```yaml
---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.1
    ports: ['5601:5601']
    networks: ['stack']

networks: {stack: {}}
```
