### ISSUE TITLE
EACCES: permission denied in the log

### ISSUE THREAD

**Issue by pvledoux** [elastic/kibana-docker#34]
Since I upgraded Kibana the 5.4 (docker image docker.elastic.co/kibana/kibana:5.4.0) I see a lot of message like this:

`kibana_1         | {"type":"log","@timestamp":"2017-05-17T10:34:33Z","tags":["error","metrics","cgroup"],"pid":1,"level":"error","message":"EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/cpuacct.usage'","error":{"message":"EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/cpuacct.usage'","name":"Error","stack":"Error: EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/cpuacct.usage'\n    at Error (native)","code":"EACCES"}}`

Indeed, /sys/fs/cgroup/cpuacct/ is owned by root. 
I saw the comment [here](https://github.com/elastic/kibana-docker/blob/master/build/kibana/bin/kibana-docker#L125) but not sure who to resolve it.

Docker version 1.13.1, build 092cba3

**Comment by dliappis** [comment]
@pvledoux Please provide information about how you run the docker image (`docker run` or `docker-compose` example) as well as the output of `docker info`. Thanks!

**Comment by pvledoux** [comment]
Hi @dliappis, I'm running it with `docker-compose up --build -d kibana`.

Docker info:

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 260
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-9:3-229638153-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.994 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.4 GB
 Metadata Space Used: 13.91 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.44 GiB
Name: 
ID: 
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Cheers,

**Comment by dliappis** [comment]
Could you please also paste your `docker-compose*.yml` files and any `.env` file you may have?

**Comment by pvledoux** [comment]
Extract of docker-compose.yml (I removed the rest of the stack): 

```
version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge

```

.env:
```
COMPOSE_PROJECT_NAME=elk
NODE_NAME=mynodename
ES_API_PORT=9200
ES_CLUSTER_PORT=9300
ES_DATA_PATH=./data/elasticsearch/
ES_SNAPSHOT_PATH=./elasticsearch/snapshots
ES_XMS=1g
ES_XMX=1g
#GIVE SOME ROOM TO DOCKER SYSTEM
DOCKER_MEM=1500m
ES_HOST_IP=127.0.0.1
ES_MASTER_NODES=1
LS_PIPELINE_WORKERS=4
LS_PIPELINE_BATCH_SIZE=1000
LS_PIPELINE_BATCH_DELAY=5
LS_HEAP_SIZE=1g
LS_LISTENING_PORT=5044
KIBANA_PORT=5601
```

**Comment by jarpy** [comment]
...and could we have `kibana.yml` please, since you are bind-mounting it into the container? Thanks.

**Comment by jarpy** [comment]
Also, it would be better to have the whole `docker-compose.yml`, since the subset provided is not valid (it depends on Elasticsearch, which is not defined). It's also not a very realistic test of Kibana to bring it up without Elasticsearch.

**Comment by jarpy** [comment]
For me, the file mentioned in the error message is world readable, so it's really interesting that it's not readable by the Kibana process in your container.

```
$ docker run --rm -it docker.elastic.co/kibana/kibana:5.4.0 stat /sys/fs/cgroup/cpuacct/cpuacct.usage
  File: '/sys/fs/cgroup/cpuacct/cpuacct.usage'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 1ch/28d Inode: 1678        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-05-19 07:10:06.681419917 +0000
Modify: 2017-05-19 07:10:06.681419917 +0000
Change: 2017-05-19 07:10:06.681419917 +0000
 Birth: -
```

**Comment by dliappis** [comment]
Lacking access to your custom `kibana.yml` file, I commented that out and added a simple elasticsearch service like below:

```
$ cat docker-compose.yml 
version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    restart: always
    #volumes:
    #  - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    restart: always
    networks:
      - docker_elk

networks:
  docker_elk:
```

```$ cat .env 
COMPOSE_PROJECT_NAME=elk
NODE_NAME=mynodename
ES_API_PORT=9200
ES_CLUSTER_PORT=9300
ES_DATA_PATH=./data/elasticsearch/
ES_SNAPSHOT_PATH=./elasticsearch/snapshots
ES_XMS=1g
ES_XMX=1g
#GIVE SOME ROOM TO DOCKER SYSTEM
DOCKER_MEM=1500m
ES_HOST_IP=127.0.0.1
ES_MASTER_NODES=1
LS_PIPELINE_WORKERS=4
LS_PIPELINE_BATCH_SIZE=1000
LS_PIPELINE_BATCH_DELAY=5
LS_HEAP_SIZE=1g
LS_LISTENING_PORT=5044
KIBANA_PORT=5601
```

I was then able to run your command:

```
docker-compose up --build -d kibana
```

and Kibana worked as expected:

```
$ curl -u elastic:changeme localhost:5601
<script>var hashRoute = '/app/kibana';
var defaultRoute = '/app/kibana';

var hash = window.location.hash;
if (hash.length) {
  window.location = hashRoute + hash;
} else {
  window.location = defaultRoute;
}
```

**Comment by pvledoux** [comment]
Ops sorry guys I totally had this issue out of my mind as Kibana is working, but just reporting this error every second or so. Here is my kibana.yml:

```
server.name: ${node_name}
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.url: "http://elasticsearch:9200"
logging.quiet: true
xpack.security.enabled: false
```

And the full docker-compose.yml:
```
version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    restart: always
    ports:
      - "${ES_API_PORT}:9200"
      - "${ES_CLUSTER_PORT}:9300"
    environment:
      - node.name=${NODE_NAME}
      - discovery.zen.minimum_master_nodes=${ES_MASTER_NODES}
      - "ES_JAVA_OPTS=-Xms${ES_XMS} -Xmx${ES_XMX}"
      - "network.bind_host=_eth0_"
      - "network.publish_host=${ES_HOST_IP}"
      - "discovery.zen.ping.unicast.hosts=${ES_DISCO_HOSTS}"
    networks:
      - docker_elk
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: ${DOCKER_MEM}
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ${ES_SNAPSHOT_PATH}:/usr/share/elasticsearch/snapshots
  logstash:
    build: logstash/
    restart: always
    environment:
      - "LS_JAVA_OPTS=-Xmx${LS_HEAP_SIZE}"
      - "node.name=${NODE_NAME}"
      - "pipeline.workers=${LS_PIPELINE_WORKERS}"
      - "pipeline.batch.size=${LS_PIPELINE_BATCH_SIZE}"
      - "pipeline.batch.delay=${LS_PIPELINE_BATCH_DELAY}"
    volumes:
      - ./logstash/patterns/:/etc/logstash/patterns/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - logstash_queue:/usr/share/logstash/queue
      - logstash_logs:/usr/share/logstash/logs
    ports:
      - "${LS_LISTENING_PORT}:5044"
      - "9600:9600"
    networks:
      - docker_elk
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  filebeat:
    build: filebeat/
    networks:
      - docker_elk
    volumes:
      - ./data:/var/data
      - filebeat_registry:/usr/share/filebeat/registry

networks:
  docker_elk:
    driver: bridge

volumes:
  esdata:
    driver: local
  essnapshots:
    driver: local
  logstash_queue:
    driver: local
  logstash_logs:
    driver: local
  filebeat_registry:
    driver: local
```

I commented out kibana.yml config and rebuild, but error is still showing up.
