### ISSUE TITLE
Unable to open Log file for Write

### ISSUE THREAD

**Issue by aconite33** [elastic/kibana-docker#50]
I'm encountering this issue.

I'm trying to write out the logs to a file on the host, shared with the Docker image. I'd like to have access the logs of kibana instead of having to print it to the screen/stdout.

Here is the error during docker-compose up
```kibana_1    | events.js:160
kibana_1    |       throw er; // Unhandled 'error' event
kibana_1    |       ^
kibana_1    | 
kibana_1    | Error: EACCES: permission denied, open '/var/log/kibana/kibana.log'
kibana_1    |     at Error (native)
panopticondockerkibana_kibana_1 exited with code 1
```

One thing to note, is that the elasticsearch docker containers will write out fine, no problem. They create the file structure for the log directory and begin writing. Kibana and Logstash don't seem to have the same luxury.

Here is my docker-compose:
```
elastic01:
 image: elasticsearch:latest
 ports:
   - "127.0.0.1:9200:9200"
 expose:
   - "9200"
   - "9300"
 command: elasticsearch -Ecluster.name="Elastic" -Ehttp.host="0.0.0.0" -Enetwork.host="0.0.0.0"
 volumes:
   - "./store/elasticsearch/data/e01:/usr/share/elasticsearch/data"
   - "./build/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
   - "./logs/elasticsearch:/usr/share/elasticsearch/logs"

elastic02:
 image: elasticsearch:latest
 links:
   - elastic01:elastic01
 command: elasticsearch -Ediscovery.zen.ping.unicast.hosts=elastic01 -Ecluster.name="Elastic" -Ehttp.host="0.0.0.0" -Enetwork.host="0.0.0.0"
 expose:
   - "9200"
   - "9300"
 volumes:
   - "./store/elasticsearch/data/e02:/usr/share/elasticsearch/data"
   - "./build/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
   - "./logs/elasticsearch:/usr/share/elasticsearch/logs"

elastic03:
 image: elasticsearch:latest
 links:
   - elastic01:elastic01
 command: elasticsearch -Ediscovery.zen.ping.unicast.hosts=elastic01 -Ecluster.name="Elastic" -Ehttp.host="0.0.0.0" -Enetwork.host="0.0.0.0"
 expose:
   - "9200"
   - "9300"
 volumes:
   - "./store/elasticsearch/data/e03:/usr/share/elasticsearch/data"
   - "./build/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
   - "./logs/elasticsearch:/usr/share/elasticsearch/logs"

logstash:
 image: logstash:latest
 ports:
   - "5044:5044"
   - "127.0.0.1:9600:9600"
 links:
   - elastic01:elastic01
 volumes:
   - "./build/logstash:/etc/logstash"
   - "./build/certs/cert.crt:/etc/pki/tls/certs/cert.crt"
   - "./build/certs/key.key:/etc/pki/tls/private/key.key"
   - "./build/logstash/log4js.properties:/etc/logstash/log4js.properties"
   - "./logs/logstash:/var/log/logstash"

kibana:
 image: kibana:latest
 ports:
   - "5601:5601"
 links:
   - elastic01:elastic01
 volumes:
   - "./build/kibana:/etc/kibana"
   - "./logs/kibana:/var/log/kibana"
```

Here is my kibana.yml
```server.host: "0.0.0.0"
elasticsearch.url: "http://elastic01:9200"
logging.dest: "/var/log/kibana/kibana.log"
```

Docker Version / Ubuntu
```Docker version 1.13.1, build 092cba3
Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
