### ISSUE TITLE
Kubernetes with docker tag 5.6.2

### ISSUE THREAD

**Issue by magicalbanana** [elastic/kibana-docker#52]
I'm having an issue when using the official image of `5.6.2` to run in a pod.

I'm using helm to install the package.

And how should the liveness and readiness be setup? Currently I have this:

```
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
```

But instead I get this error:
```
Readiness probe failed: Get http://10.0.1.42:5601/: dial tcp 10.0.1.42:5601: getsockopt: connection refused
```

And when it does run, I get this issue:

![image](https://user-images.githubusercontent.com/7953984/31413775-9d1fb278-ade0-11e7-85bf-a8e575e736dd.png)
