### ISSUE TITLE
Problem with rc2 image

### ISSUE THREAD

**Issue by ctindel** [elastic/kibana-docker#56]
I didn't have this issue at first, but I removed all my images and re-pulled everything, is it possible that something was re-built and re-pushed with a typo in the kibana.yml or something?  

docker logs -f sa-demo-apachelogs-kibana-build
{"type":"log","@timestamp":"2017-11-04T04:23:43Z","tags":["fatal"],"pid":1,"message":"\"xpack.monitoring.ui.container.elasticsearch.enabled\" setting was not applied. Check for spelling errors and ensure that expected plugins are installed and enabled."}

I don't even set XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED in my docker-compose file, the kibana portion looks like this:

```
  sa-demo-apachelogs-kibana-build:
    image: docker.elastic.co/kibana/kibana:6.0.0-rc2
    depends_on:
      - sa-demo-apachelogs-es-build
    container_name: sa-demo-apachelogs-kibana-build
    environment:
      XPACK_MONITORING_ENABLED: "false"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      XPACK_SECURITY_SECURECOOKIES: "true"
    ports:
      - 5601:5601
    networks:
      sa-demo-apachelogs-build-net:
        aliases:
          - kibana
```

I've recreated it with a minimal docker-compose.yml here:

```
$ cat docker-compose.yml
version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0-rc2
    container_name: kibana
    environment:
      XPACK_MONITORING_ENABLED: "false"
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      XPACK_SECURITY_SECURECOOKIES: "true"
    ports:
      - 5601:5601
$ docker-compose up
Creating network "tmp_default" with the default driver
Creating kibana
Attaching to kibana
kibana    | {"type":"log","@timestamp":"2017-11-04T04:52:17Z","tags":["fatal"],"pid":1,"message":"\"xpack.monitoring.ui.container.elasticsearch.enabled\" setting was not applied. Check for spelling errors and ensure that expected plugins are installed and enabled."}
kibana exited with code 64
```
