### ISSUE TITLE
Errors with userns-remap

### ISSUE THREAD

**Issue by frederikbosch** [elastic/kibana-docker#92]
When running docker with [`userns-remap`](https://docs.docker.com/engine/security/userns-remap/), which is recommended by security standards, Kibana is not able to boot by default. This is due to the fact that `/usr/share/kibana/optimize` is not writeable for `.babelcache.json` and `bundles`. Further, `/usr/share/kibana/data` has to be made accessible too.

```yaml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    restart: on-failure:5
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch1:9200
    ports:
    - 5601:5601
    networks:
    - esnet
```

When I add this to the config, and I do a chmod 0777 on the .cache directory, it works. Named volumes do not work.

```
    volumes:
    - ./.cache/cache:/usr/share/kibana/optimize
    - ./.cache/data:/usr/share/kibana/data
```
